# ============================================================================
# CORREÇÃO: Mensagem Duplicada de Validação (Salvo + Erro)
# ============================================================================

cat("════════════════════════════════════════════════════════════════════════\n")
cat("✅ CORREÇÃO: Validação sem Mensagens Duplicadas\n")
cat("════════════════════════════════════════════════════════════════════════\n\n")

cat("🔴 PROBLEMA:\n")
cat("─────────────────────────────────────────────────────────────────────────\n")
cat("Ao clicar em botão de validação, via:\n")
cat("  ✅ Validação salva com sucesso!\n")
cat("  ❌ Dados não encontrados em nenhuma fonte\n")
cat("  ✅ Modelo ML carregado do disco\n")
cat("Tudo simultaneamente - mensagens conflitantes\n\n")

cat("CAUSA RAIZ:\n")
cat("  • observe({ req(values$resultados_lote) }) criava 300 observeEvents\n")
cat("  • Quando values$resultados_lote mudava → ALL 300 são recriados\n")
cat("  • Enquanto você validava, observe() era acionado NOVAMENTE\n")
cat("  • Criava observeEvents DUPLICADOS para mesmo botão\n")
cat("  • Ambos respondiam ao clique → mensagens conflitantes\n\n")

cat("✅ SOLUÇÃO:\n")
cat("─────────────────────────────────────────────────────────────────────────\n")
cat("Usar apenas UM observeEvent CENTRALIZADO que:\n\n")

cat("1. Intercepta session$lastInputId (qualquer input acionado)\n")
cat("2. Verifica se começa com 'validar_ml_'\n")
cat("3. Extrai ID da nota e tipo do botão\n")
cat("4. Chama salvar_validacao_ml COM DADOS ATUALIZADOS\n")
cat("5. Mostra uma mensagem (sucesso OU erro, não ambas)\n\n")

cat("VANTAGENS:\n")
cat("  ✓ Apenas 1 observeEvent para TODOS os 300 botões\n")
cat("  ✓ Sem duplicatas\n")
cat("  ✓ Sem conflito de handlers\n")
cat("  ✓ Sem overhead de recriação\n")
cat("  ✓ Dados sempre dinâmicos e atualizados\n\n")

cat("📁 ARQUIVOS ATUALIZADOS:\n")
cat("─────────────────────────────────────────────────────────────────────────\n")
cat("1. CLASSIFICADOR_VERSAO14.R (linhas 8017-8064)\n")
cat("2. CLASSIFICADOR_VERSAO14 copy.R (linhas 8100-8147)\n\n")

cat("🧪 TESTE:\n")
cat("─────────────────────────────────────────────────────────────────────────\n")
cat("1. Classificar lote de 50 textos\n")
cat("2. Clicar em validar_ml_[ID]_[TIPO]\n")
cat("3. Esperado: APENAS UMA mensagem\n")
cat("   • ✅ Validação salva: [ID] → Tipo [TIPO]  (sucesso)\n")
cat("   • OU\n")
cat("   • ❌ Erro ao salvar validação para [ID]   (erro)\n")
cat("4. NÃO deve ver ambas as mensagens\n")
cat("5. Console deve mostrar:\n")
cat("   📝 Botão clicado: validar_ml_[ID]_[TIPO]\n")
cat("   ID extraído: [ID]\n")
cat("   Tipo extraído: [TIPO]\n")
cat("   ✓ Usando dados passados como parâmetro\n")
cat("   ✅ Validação salva com sucesso!\n\n")

cat("💡 ALTERNATIVA SE AINDA NÃO FUNCIONAR:\n")
cat("─────────────────────────────────────────────────────────────────────────\n")
cat("Se session$lastInputId não funcionar (versão Shiny antiga),\n")
cat("pode usar input_id via reatividade:\n")
cat("  reactiveVal(input_id) e depois monitorar mudanças\n")
cat("Mas session$lastInputId é mais simples e funciona em Shiny > 1.5\n\n")

cat("════════════════════════════════════════════════════════════════════════\n")
cat("✅ VALIDAÇÃO AGORA SEM MENSAGENS CONFLITANTES\n")
cat("════════════════════════════════════════════════════════════════════════\n")
